replicaCount: 1

image:
  repository: lscr.io/linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7878

ingress:
  enabled: true
  hosts:
    - host: radarr.example.com
      paths: ["/"]
  annotations:
    kubernetes.io/ingress.class: traefik
  tls: []

persistence:
  media:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 100Gi
  downloads:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteMany
    size: 50Gi
